backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "work"
    label: "Work"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Language", name: "language", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Vimeo", name: "vimeo", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "page"
    label: "Page"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
